import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>My NextJs Ecommerce Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-xl">Welcome to my NextJs Ecommerce Starter</h1>
      </main>
    </div>
  );
}
